# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 769ef2248172f2f835baca2cc6dd6f17a70d5d69283d5ed56cab18988078be112ce500de5108eb66e0ea48828a52d7a0e740fe670c50ba48468ffb0a895cb5a1

test:
  secret_key_base: c8879db0741439785234cd689dbb24b339befb5d98b6255ddff618a308c69477c8aeb6c52a30a5293cda0fe959fcee529eb6dac1bea64e5c6b250162727ae64f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
